name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GO111MODULE: "on"
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Build
        run: go build -v .
